// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

public extension Bot {

    /// Parameters container struct for `getMyDefaultAdministratorRights` method
    struct GetMyDefaultAdministratorRightsParams: JSONEncodable {

        /// Pass True to get default administrator rights of the bot in channels. Otherwise, default administrator rights of the bot for groups and supergroups will be returned.
        var forChannels: Bool?

        /// Custom keys for coding/decoding `GetMyDefaultAdministratorRightsParams` struct
        enum CodingKeys: String, CodingKey {
            case forChannels = "for_channels"
        }

        public init(forChannels: Bool? = nil) {
            self.forChannels = forChannels
        }
    }

    /**
     Use this method to get the current default administrator rights of the bot. Returns ChatAdministratorRights on success.

     SeeAlso Telegram Bot API Reference:
     [GetMyDefaultAdministratorRightsParams](https://core.telegram.org/bots/api#getmydefaultadministratorrights)
     
     - Parameters:
         - params: Parameters container, see `GetMyDefaultAdministratorRightsParams` struct
     - Throws: Throws on errors
     - Returns: Future of `ChatAdministratorRights` type
     */
    @discardableResult
    func getMyDefaultAdministratorRights(params: GetMyDefaultAdministratorRightsParams? = nil) throws -> Future<ChatAdministratorRights> {
        let body = try httpBody(for: params)
        let headers = httpHeaders(for: params)
        return try client
            .request(endpoint: "getMyDefaultAdministratorRights", body: body, headers: headers)
            .flatMapThrowing { (container) -> ChatAdministratorRights in
                return try self.processContainer(container)
        }
    }
}

// MARK: Concurrency Support
#if compiler(>=5.5)
@available(macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0, *)
public extension Bot {

    /**
     Use this method to get the current default administrator rights of the bot. Returns ChatAdministratorRights on success.

     SeeAlso Telegram Bot API Reference:
     [GetMyDefaultAdministratorRightsParams](https://core.telegram.org/bots/api#getmydefaultadministratorrights)
     
     - Parameters:
         - params: Parameters container, see `GetMyDefaultAdministratorRightsParams` struct
     - Throws: Throws on errors
     - Returns: Future of `ChatAdministratorRights` type
     */
    @discardableResult
    func getMyDefaultAdministratorRights(params: GetMyDefaultAdministratorRightsParams? = nil) async throws -> ChatAdministratorRights {
        let body = try httpBody(for: params)
        let headers = httpHeaders(for: params)
        return try self.processContainer(try await client.request(endpoint: "getMyDefaultAdministratorRights", body: body, headers: headers))
    }
}
#endif
