// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

public extension Bot {

    /// Parameters container struct for `declineChatJoinRequest` method
    struct DeclineChatJoinRequestParams: JSONEncodable {

        /// Unique identifier for the target chat or username of the target channel (in the format @channelusername)
        var chatId: ChatId

        /// Unique identifier of the target user
        var userId: Int64

        /// Custom keys for coding/decoding `DeclineChatJoinRequestParams` struct
        enum CodingKeys: String, CodingKey {
            case chatId = "chat_id"
            case userId = "user_id"
        }

        public init(chatId: ChatId, userId: Int64) {
            self.chatId = chatId
            self.userId = userId
        }
    }

    /**
     Use this method to decline a chat join request. The bot must be an administrator in the chat for this to work and must have the can_invite_users administrator right. Returns True on success.

     SeeAlso Telegram Bot API Reference:
     [DeclineChatJoinRequestParams](https://core.telegram.org/bots/api#declinechatjoinrequest)
     
     - Parameters:
         - params: Parameters container, see `DeclineChatJoinRequestParams` struct
     - Throws: Throws on errors
     - Returns: Future of `Bool` type
     */
    @discardableResult
    func declineChatJoinRequest(params: DeclineChatJoinRequestParams) throws -> Future<Bool> {
        let body = try httpBody(for: params)
        let headers = httpHeaders(for: params)
        return try client
            .request(endpoint: "declineChatJoinRequest", body: body, headers: headers)
            .flatMapThrowing { (container) -> Bool in
                return try self.processContainer(container)
        }
    }
}

// MARK: Concurrency Support
#if compiler(>=5.5)
@available(macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0, *)
public extension Bot {

    /**
     Use this method to decline a chat join request. The bot must be an administrator in the chat for this to work and must have the can_invite_users administrator right. Returns True on success.

     SeeAlso Telegram Bot API Reference:
     [DeclineChatJoinRequestParams](https://core.telegram.org/bots/api#declinechatjoinrequest)
     
     - Parameters:
         - params: Parameters container, see `DeclineChatJoinRequestParams` struct
     - Throws: Throws on errors
     - Returns: Future of `Bool` type
     */
    @discardableResult
    func declineChatJoinRequest(params: DeclineChatJoinRequestParams) async throws -> Bool {
        let body = try httpBody(for: params)
        let headers = httpHeaders(for: params)
        return try self.processContainer(try await client.request(endpoint: "declineChatJoinRequest", body: body, headers: headers))
    }
}
#endif
